Repository unlimited-excellence/horse-dao, pull requests merged in 2025-02, with the labels that each got.

#20 Update README.md
  README.md
Labels: documentation

#21 Cleaned up the whole project
  main.py
  test_file_by_LaGipeR-v2.txt
Labels: cleanup and refactor

#26 Added `Main Branch Workflow`, which builds badges on push; also added…
  .github/workflows/main-branch.yml
  README.md
Labels: documentation

#27 Added GitHub Workflow to link new branches to issues
  .github/workflows/link-branch-to-issue.yml
Labels: enhancement

#32 feature/issue-14-connect-telegram-bot
  bot/telegram_bot.py
  db/mongo_client.py
  endpoints/telegram.py
  main.py
  requirements.txt
  services/user_service.py
Labels: enhancement

#36 Created NotificationsService and now sending random message on `/start` after 5s
  endpoints/telegram.py
  main.py
  services/NotificationsService.py
Labels: enhancement, help wanted
